version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Root password for MySQL
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Default database name
      MYSQL_USER: ${MYSQL_USER}                    # Additional user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}            # Password for the additional user
      MYSQL_ROOT_HOST: '%'
    ports:
      - "${MYSQL_PORT}:3306"                       # Host to container port mapping
    volumes:
      - mysql_data:/var/lib/mysql                  # Persistent data storage
    networks:
      - mysql_network

volumes:
  mysql_data:                                       # Named volume for MySQL data

networks:
  mysql_network:                                   # Network for the container